# Generated by Django 2.0 on 2017-12-10 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20171210_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_pic', models.ImageField(blank=True, default='RIDER_PIC', upload_to='Rider/prof_pic')),
                ('gender', models.CharField(blank=True, choices=[('F', 'female'), ('M', 'male'), ('Both', 'both'), ('None', 'non-specified')], default='None', max_length=30)),
                ('home_address', models.CharField(blank=True, max_length=255)),
                ('rider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Rider')),
            ],
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='prof_pic',
            field=models.ImageField(blank=True, default='DRIVER_PIC', upload_to='Driver/profile_pic'),
        ),
    ]
