# Generated by Django 2.0 on 2017-12-10 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20171210_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Driver')),
                ('rider_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.RiderProfile')),
            ],
        ),
    ]
