# Generated by Django 2.0 on 2017-12-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20171212_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='car_capacity',
            field=models.PositiveIntegerField(blank=True, default=5),
        ),
    ]
