# Generated by Django 2.0 on 2017-12-12 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20171212_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riderprofile',
            old_name='home_address',
            new_name='general_location',
        ),
    ]
