# Generated by Django 2.0 on 2017-12-06 10:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rider'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='password',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rider',
            name='password',
            field=models.CharField(default=datetime.datetime(2017, 12, 6, 10, 3, 17, 745013, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
