# Generated by Django 2.0 on 2017-12-10 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_riderreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('driver_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Driver')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Rider')),
            ],
        ),
    ]
