# Generated by Django 2.0 on 2017-12-11 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_driverreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='driverreview',
            name='driver_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.DriverProfile'),
        ),
        migrations.AlterField(
            model_name='rider',
            name='city',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='rider',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='rider',
            name='phone',
            field=models.PositiveIntegerField(),
        ),
    ]
