# Generated by Django 2.0 on 2017-12-11 20:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20171211_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='email',
            field=models.EmailField(default=datetime.datetime(2017, 12, 11, 20, 54, 33, 322301, tzinfo=utc), max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driver',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='rider',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
