# Generated by Django 2.0 on 2017-12-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20171211_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='gender',
            field=models.TextField(blank=True, choices=[('Female', 'female'), ('Male', 'male'), ('Both', 'both'), ('None', 'non-specified')], default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'female'), ('Male', 'male'), ('Both', 'both'), ('None', 'non-specified')], default='None', max_length=30),
        ),
    ]
