# Generated by Django 2.0 on 2017-12-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20171212_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='car_color',
            field=models.CharField(blank=True, default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='car_plate',
            field=models.CharField(blank=True, default='None', max_length=255),
        ),
    ]
