# Generated by Django 2.0 on 2017-12-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20171212_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='prof_pic',
            field=models.ImageField(blank=True, default='DRIVER_PIC', upload_to='Driver/prof_pic'),
        ),
    ]
