# Generated by Django 2.0 on 2017-12-12 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20171212_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDriver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DriverJourney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('driver_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.DriverProfile')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.AddField(
            model_name='bookdriver',
            name='driver_journey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.DriverJourney'),
        ),
        migrations.AddField(
            model_name='bookdriver',
            name='rider_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.RiderProfile'),
        ),
    ]
